### ISSUE TITLE
Running Examples on Mathematica 12.3 Don't work 

### ISSUE THREAD

**Issue by MKAbdElrahman** [c3m-labs/ImportMesh#6]
I got the following error after trying to import any mesh.

ToElementMesh::fembdct: The coordinates {{Internal`StringToDouble[10.0000],Internal`StringToDouble[0.0000],Internal`StringToDouble[0.0000]},{Internal`StringToDouble[9.2388],Internal`StringToDouble[3.8268],Internal`StringToDouble[0.0000]},<<7>>,{Internal`StringToDouble[3.8268],Internal`StringToDouble[9.2388],Internal`StringToDouble[0.0000]},<<70>>} are not of type real.

**Comment by PintarM** [comment]
Hi!

Can you please give me some more information what you have tried? What is the input file, code that you tried and versions of Mathematica and this package. 

I have run the testing suite for this package in Mathematica 12.2 and everything passes ok. I am not sure if version 12.3 is released already?

**Comment by ruebenko** [comment]
@PintarM 
In version 12.3 the following renaming of internal functions was / will be done:
DoubleToString -> MRealToString
StringToDouble -> StringToMReal

At the point of writing this V12.3 is not yet released.

**Comment by MKAbdElrahman** [comment]
Thank you. It's working fine now.

**Comment by PintarM** [comment]
Hi @ruebenko ,
Thank you for the explanation.

Since all functionality from this repo is now included in FEMAddOns, I decided that I will no longer maintain it.
I will include a warning in README file to point users your way. ;)

**Comment by ruebenko** [comment]
Sounds good to me. There i have fixed the issue yesterday.
